/* Generated by scripts/import_products.py from the store export. Do not edit by hand. */
window.PRODUCTS = [
  {
    "handle": "lavan-earrings",
    "name": {
      "fa": "گوشواره لاوان",
      "en": "Lavan Earrings"
    },
    "desc": {
      "fa": "با الهام از طبیعت جنوب ایران",
      "en": "Inspired by the nature of southern Iran."
    },
    "category": "earrings",
    "collection": null,
    "price": 38000000,
    "stock": 2,
    "images": []
  },
  {
    "handle": "gulf-earrings",
    "name": {
      "fa": "گوشواره خلیج",
      "en": "Gulf Earrings"
    },
    "desc": {
      "fa": "با الهام از طبیعت جنوب ایران",
      "en": "Inspired by the nature of southern Iran."
    },
    "category": "earrings",
    "collection": null,
    "price": 180000000,
    "stock": 5,
    "images": []
  },
  {
    "handle": "tt-earrings",
    "name": {
      "fa": "گوشواره تی تی",
      "en": "Titi Earrings"
    },
    "desc": {
      "fa": "تجربه‌هایی که در طول زندگی همراه خودمون حمل میکنیم.هربار با دست ساخته میشود.",
      "en": "The experiences we carry with us through life. Made by hand, every time."
    },
    "category": "earrings",
    "collection": null,
    "price": 88000000,
    "stock": 1,
    "images": [
      "https://core.doorfestival.com/static/1779131056606-332404c1-0e64-4a01-9359-f78477f25f74.png",
      "https://core.doorfestival.com/static/1779131056607-fa2b89b4-5754-409f-83f6-09a363a5f47f.png"
    ]
  },
  {
    "handle": "ahil-and-pearl-earrings",
    "name": {
      "fa": "گوشواره آهیل و مروارید",
      "en": "Ahil & Pearl Earrings"
    },
    "desc": {
      "fa": "رد اتفاقاتی که همراه ما می‌ماند.هربار با دست ساخته میشود\nمروارید آب شیرین",
      "en": "Traces of the moments that stay with us. Made by hand, every time. Freshwater pearl."
    },
    "category": "earrings",
    "collection": null,
    "price": 90000000,
    "stock": 1,
    "images": [
      "https://core.doorfestival.com/static/1781862974706-93553b4cdfe94cb301d225daec5324e0.jpg"
    ]
  },
  {
    "handle": "ircaf-silver-douran",
    "name": {
      "fa": "ایرکاف نقره دوران",
      "en": "Douran Silver Ear Cuff"
    },
    "desc": {
      "fa": "۳ گرم",
      "en": "3 grams."
    },
    "category": "earrings",
    "collection": null,
    "price": 58000000,
    "stock": 5,
    "images": [
      "https://core.doorfestival.com/static/1781863669942-dc3038de36ab9c21a1980b5f98103c84.jpg",
      "https://core.doorfestival.com/static/1781863669944-27bde4afeff0b9888e39b90f684bebf1.jpg"
    ]
  },
  {
    "handle": "still-necklace",
    "name": {
      "fa": "گردنبند هنوز",
      "en": "Still Necklace"
    },
    "desc": {
      "fa": "این گردنبند نقره از مجموعه Flower Power با فرمی الهام‌گرفته از گل‌های شهری طراحی شده؛\n\nفرمی که نامنظم، زنده و بدون تلاش برای کامل‌بودن است.\n\nگردنبند Anyway نمادی از رشد و تداوم «با وجودِ همه‌چیز» است؛\n\nفرمی که باقی مانده، نه تزئین شده.\n\nاین گردنبند با زنجیر نقره در دو طول ۴۰ و ۵۰ سانتی‌متر قابل سفارش است.",
      "en": "A silver necklace from the Flower Power collection, shaped after urban flowers: irregular, alive, and not trying to be perfect. A sign of growth and carrying on, despite everything. Available on a 40 or 50 cm silver chain."
    },
    "category": "necklaces",
    "collection": "flower-power",
    "price": 118000000,
    "stock": 1,
    "images": []
  },
  {
    "handle": "darakoh-silver-ring",
    "name": {
      "fa": "انگشتر نقره درکوه",
      "en": "Dar-e Kuh Silver Ring"
    },
    "desc": {
      "fa": "انگشتر \"در کوه\"از مجموعه‌ی کائوس با الهام از طبیعت جنوب ساخته شده است.",
      "en": "The “Dar-e Kuh” ring from the Chaos collection, inspired by the nature of southern Iran."
    },
    "category": "rings",
    "collection": "chaos",
    "price": 88000000,
    "stock": 1,
    "images": []
  },
  {
    "handle": "silver-smooth-earrings",
    "name": {
      "fa": "گوشواره نقره روان",
      "en": "Ravan Silver Earrings"
    },
    "desc": {
      "fa": "گوشواره نقره «روان» از مجموعه Flower Power با فرمی گل‌گونه و خطوطی سیال طراحی شده که حس حرکت و جریان آزاد را تداعی می‌کند.\n\nساختار توخالی و لبه‌های نرم آن، نور را از میان خود عبور می‌دهد و جلوه‌ای ظریف اما متفاوت روی گوش ایجاد می‌کند.",
      "en": "From the Flower Power collection: a flower-like form with fluid lines that suggest free movement. Its hollow shape and soft edges let light pass through."
    },
    "category": "earrings",
    "collection": "flower-power",
    "price": 70000000,
    "stock": 1,
    "images": [
      "https://c366733.parspack.net/c366733//IMG_4693_11zon-01KZGQ4MQ0YZC5NXFY9TYTFPEM.jpg",
      "https://c366733.parspack.net/c366733//d_11zon-01KZGQ4MQ2KS8EC8VPVEQBK58A.jpg"
    ]
  },
  {
    "handle": "invisible-silver-earrings",
    "name": {
      "fa": "گوشواره نقره ناپیدا",
      "en": "Napeyda Silver Earrings"
    },
    "desc": {
      "fa": "گوشواره نقره \"ناپیدا\" از مجموعه \"FLOWER POWER\" در تلاش برای نشان دادن است رَدی است که ممکن است ناپیدا باشد ولی بی اثر نیست.",
      "en": "From the Flower Power collection: a trace that may be invisible, but is never without effect."
    },
    "category": "earrings",
    "collection": "flower-power",
    "price": 80000000,
    "stock": 1,
    "images": [
      "https://c366733.parspack.net/c366733//IMG_4027_11zon_11zon_11zon_11zon-01KZGQA4VETRQ2D3N4SJR72AFW.jpg",
      "https://c366733.parspack.net/c366733//IMG_36605_11zon-01KZGQA4VG4KKABCD356KDHPQQ.jpg"
    ]
  },
  {
    "handle": "stud-earring",
    "name": {
      "fa": "گوشواره یال",
      "en": "Yal Earrings"
    },
    "desc": {
      "fa": "نقره و مروارید آب شیرین",
      "en": "Silver and freshwater pearl."
    },
    "category": "earrings",
    "collection": null,
    "price": 120000000,
    "stock": 1,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3480-01M48V9C49KJF6V7TM36963S1N.webp",
      "https://c366733.parspack.net/c366733/static/IMG_3482-01M48V9C4E9YZZE5Y1EJHC9F4X.webp"
    ]
  },
  {
    "handle": "double-sided-earrings",
    "name": {
      "fa": "گوشواره رو در رو",
      "en": "Face to Face Earrings"
    },
    "desc": {
      "fa": "نقره",
      "en": "Silver."
    },
    "category": "earrings",
    "collection": null,
    "price": 180000000,
    "stock": 4,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3478-01M48V7FQC934HBKSGRKVW9ZA0.webp"
    ]
  },
  {
    "handle": "chinese-cloud-chest-stud",
    "name": {
      "fa": "سنجاق سینه ابر چینی",
      "en": "Chinese Cloud Brooch"
    },
    "desc": {
      "fa": "نقره",
      "en": "Silver."
    },
    "category": "brooches",
    "collection": null,
    "price": 180000000,
    "stock": 4,
    "images": [
      "https://c366733.parspack.net/c366733/static/photo_2026-10-06 18.20.29-01M48V5CJYGYQSV0TD5NJJ0CR2.webp",
      "https://c366733.parspack.net/c366733/static/photo_2026-10-06 18.20.32-01M48V5CJZVDT8VN4MTWQWF1HN.webp",
      "https://c366733.parspack.net/c366733/static/photo_2026-10-06 18.20.36-01M48V5CK0FBAEWP5FZW0BCMHG.webp"
    ]
  },
  {
    "handle": "once-upon-a-time-earring",
    "name": {
      "fa": "گوشواره یکی بود یکی نبود",
      "en": "Once Upon a Time Earrings"
    },
    "desc": {
      "fa": "نقره",
      "en": "Silver."
    },
    "category": "earrings",
    "collection": null,
    "price": 180000000,
    "stock": 1,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3483-01M48V2K5ZZZVG20PDE3PQHZB8.webp"
    ]
  },
  {
    "handle": "carousel-necklace",
    "name": {
      "fa": "گردنبند مانژ",
      "en": "Carousel Necklace"
    },
    "desc": {
      "fa": "نقره",
      "en": "Silver."
    },
    "category": "necklaces",
    "collection": null,
    "price": 120000000,
    "stock": 3,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3469-01M48V1QE23WZMVFWXX7Z2TJ3M.webp"
    ]
  },
  {
    "handle": "tuscan-earrings",
    "name": {
      "fa": "گوشواره توسن",
      "en": "Tosan Earrings"
    },
    "desc": {
      "fa": "نقره",
      "en": "Silver."
    },
    "category": "earrings",
    "collection": null,
    "price": 140000000,
    "stock": 1,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3485-01M48TZX2F4QNCKDFAYK5Y4B5V.webp"
    ]
  },
  {
    "handle": "horse-fancy-ring",
    "name": {
      "fa": "انگشتر خیال یک اسب",
      "en": "Dream of a Horse Ring"
    },
    "desc": {
      "fa": "نقره",
      "en": "Silver."
    },
    "category": "rings",
    "collection": null,
    "price": 90000000,
    "stock": 6,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3470-01M48TXTC9NYDJWG3P2SVJ5DHA.webp",
      "https://c366733.parspack.net/c366733/static/IMG_3471-01M48TXTCAWBA6R8QR4H333N66.webp",
      "https://c366733.parspack.net/c366733/static/IMG_3472-01M48TXTCBDJ6P7QVK4CKT8G0R.webp"
    ]
  },
  {
    "handle": "mint-ring",
    "name": {
      "fa": "انگشتر نوند",
      "en": "Navand Ring"
    },
    "desc": {
      "fa": "نقره",
      "en": "Silver."
    },
    "category": "rings",
    "collection": null,
    "price": 100000000,
    "stock": 4,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3475-01M48TVYV7PJKRP1D1SF9NEDP8.webp",
      "https://c366733.parspack.net/c366733/static/IMG_3476-01M48TVYVFK25SSG0PG5YTYPK3.webp"
    ]
  },
  {
    "handle": "horse-necklace",
    "name": {
      "fa": "گردنبند یک اسب",
      "en": "A Horse Necklace"
    },
    "desc": {
      "fa": "نقره",
      "en": "Silver."
    },
    "category": "necklaces",
    "collection": null,
    "price": 120000000,
    "stock": 4,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3477-01M48TT90RV335A9EM48K0F4ZY.webp"
    ]
  },
  {
    "handle": "chocolate-cake",
    "name": {
      "fa": "چوکر تاختن",
      "en": "Galloping Choker"
    },
    "desc": {
      "fa": "نقره و بند برنجی",
      "en": "Silver and brass cord."
    },
    "category": "necklaces",
    "collection": null,
    "price": 100000000,
    "stock": 0,
    "images": [
      "https://c366733.parspack.net/c366733/static/IMG_3487-01M48TP1X6G3W6SENTHVR454VS.webp"
    ]
  }
];
